export type MusicStyle = {
  slug: string; name: string; region: string; family: string; mood: string;
  bpm: string; instruments: string; groove: string; vocal: string; prompt: string; exclude: string;
  referenceTracks?: MusicReferenceTrack[];
};

export type MusicReferenceTrack = {
  id: string;
  label: string;
  audioUrl: string;
  direction: string;
};

export const musicStyles: MusicStyle[] = [
  {slug:"sertanejo-universitario",name:"Sertanejo universitário",region:"Centro-Oeste",family:"Sertanejo",mood:"romântico, direto e radiofônico",bpm:"96–112",instruments:"violão de aço, sanfona discreta, baixo redondo, bateria pop",groove:"balanço em 4/4 com refrão aberto",vocal:"dueto expressivo, dicção brasileira natural",prompt:"Contemporary Brazilian sertanejo universitário, warm acoustic steel guitar, subtle accordion, polished pop drums, rounded bass, intimate verses building into a wide singalong chorus, emotional Brazilian Portuguese vocal, memorable melodic hook, modern clean production",exclude:"country americano, banjo, bluegrass, sotaque estrangeiro, vocal excessivamente melismático"},
  {slug:"modao",name:"Modão sertanejo",region:"Interior do Brasil",family:"Sertanejo",mood:"saudade, perda e verdade",bpm:"68–88",instruments:"viola caipira, violão, acordeon, baixo acústico",groove:"lento, marcado e narrativo",vocal:"voz madura, sofrida, sem exagero",prompt:"Traditional Brazilian sertanejo modão, expressive viola caipira, acoustic guitar, gentle accordion, slow steady rhythm, spacious arrangement, heartfelt storytelling, mature Brazilian Portuguese lead vocal, bittersweet melody, organic room sound",exclude:"trap drums, synth bass, EDM, country rock americano, autotune evidente"},
  {slug:"piseiro",name:"Piseiro",region:"Nordeste",family:"Forró",mood:"dançante, simples e viciante",bpm:"150–170",instruments:"teclado, sanfona sintética, zabumba eletrônica, baixo",groove:"pisada reta e repetitiva",vocal:"frases curtas, chamadas e resposta",prompt:"Brazilian piseiro from the Northeast, fast danceable pulse, punchy electronic zabumba, bright keyboard accordion, syncopated bass, minimal arrangement, short catchy vocal phrases, call and response, playful Brazilian Portuguese delivery, instantly repeatable chorus",exclude:"rock guitars, orchestral strings, slow intro, vocal lírico, arranjo denso"},
  {slug:"forro-pe-de-serra",name:"Forró pé de serra",region:"Nordeste",family:"Forró",mood:"festivo, humano e tradicional",bpm:"118–138",instruments:"sanfona, zabumba, triângulo",groove:"baião dançante de trio",vocal:"popular, caloroso e próximo",prompt:"Authentic Brazilian forró pé de serra trio, lively accordion, deep zabumba, crisp triangle, organic dance groove, joyful rustic atmosphere, warm Brazilian Portuguese vocal, catchy refrain, live ensemble feel, dynamic instrumental breaks",exclude:"electronic drums, EDM risers, electric guitar wall, synth pads, pop americano"},
  {slug:"baiao",name:"Baião",region:"Nordeste",family:"Forró",mood:"forte, telúrico e viajante",bpm:"92–116",instruments:"sanfona, zabumba, triângulo, rabeca",groove:"célula sincopada de baião",vocal:"narrativo com imagens do Brasil",prompt:"Brazilian baião, syncopated zabumba pattern, expressive accordion, triangle and occasional rabeca, earthy forward motion, cinematic Northeastern landscape, narrative Brazilian Portuguese vocal, strong melodic motif, organic acoustic production",exclude:"four-on-the-floor EDM, trap hi-hats, country americano, coral épico, timbres futuristas"},
  {slug:"arrocha",name:"Arrocha",region:"Bahia",family:"Romântico",mood:"sofrência, desejo e madrugada",bpm:"68–86",instruments:"teclado, guitarra limpa, baixo, bateria lenta",groove:"balada dançante e sentimental",vocal:"íntimo, rouco e confessional",prompt:"Brazilian arrocha, slow sensual dance rhythm, emotional keyboard harmony, clean electric guitar fills, deep bass, restrained drums, intimate late-night atmosphere, vulnerable Brazilian Portuguese vocal, dramatic pre-chorus and addictive heartbreak chorus",exclude:"rock pesado, samba percussion, EDM drop, vocal operístico, andamento rápido"},
  {slug:"pagode-90",name:"Pagode romântico 90",region:"Sudeste",family:"Samba e pagode",mood:"romântico, solar e nostálgico",bpm:"88–104",instruments:"cavaquinho, tantan, pandeiro, repique de mão",groove:"swing de pagode macio",vocal:"lead suave com coro responsivo",prompt:"Brazilian 1990s-inspired romantic pagode, warm cavaquinho, tantan, pandeiro and hand repique, smooth syncopated samba groove, rich vocal harmonies, tender Brazilian Portuguese lead, conversational verses, uplifting memorable chorus, polished yet organic band sound",exclude:"trap beat, EDM synths, bateria de rock, samba-enredo acelerado, vocal estrangeiro"},
  {slug:"pagode-atual",name:"Pagode atual",region:"Brasil urbano",family:"Samba e pagode",mood:"leve, apaixonado e moderno",bpm:"92–108",instruments:"cavaquinho, percussão de pagode, baixo elétrico, teclas",groove:"swing limpo com pausas para o hook",vocal:"conversado, jovem, com ad-libs",prompt:"Contemporary Brazilian pagode, crisp cavaquinho, modern pagode percussion, melodic electric bass, subtle keys, clean urban mix, relaxed syncopation, conversational Brazilian Portuguese vocal, strategic pauses, catchy relationship hook, crowd-ready chorus",exclude:"funk beat dominante, axé, guitarras distorcidas, excesso de reverb, coral gospel"},
  {slug:"samba-raiz",name:"Samba de raiz",region:"Rio de Janeiro",family:"Samba e pagode",mood:"comunitário, poético e vivo",bpm:"88–108",instruments:"cavaquinho, violão 7 cordas, surdo, pandeiro, cuíca",groove:"samba sincopado de roda",vocal:"natural, coletivo e narrativo",prompt:"Authentic Brazilian samba de raiz, cavaquinho, seven-string guitar counterlines, surdo, pandeiro and subtle cuíca, lively roda de samba feel, poetic Brazilian Portuguese storytelling, natural lead vocal with communal responses, organic live dynamics",exclude:"quantized electronic drums, synthwave, rock guitars, pop americano, autotune pesado"},
  {slug:"samba-rock",name:"Samba-rock",region:"São Paulo",family:"Samba e soul",mood:"elegante, urbano e dançante",bpm:"104–122",instruments:"guitarra wah, baixo funk, metais, percussão",groove:"samba com pocket de funk/soul",vocal:"swingado e confiante",prompt:"São Paulo Brazilian samba-rock, tight funk bass, syncopated samba percussion, clean wah guitar, punchy horn accents, stylish urban groove, confident Brazilian Portuguese vocal, rhythmic verses and infectious dance chorus, warm analog character",exclude:"hard rock, EDM drop, trap hi-hats, andamento lento, arranjo acústico rural"},
  {slug:"mpb",name:"MPB contemporânea",region:"Brasil",family:"MPB",mood:"poética, íntima e sofisticada",bpm:"72–104",instruments:"violão nylon, piano, baixo, percussão sutil",groove:"orgânico com síncopes discretas",vocal:"próximo, interpretativo e humano",prompt:"Contemporary Brazilian MPB, intimate nylon-string guitar, expressive piano, lyrical bass and subtle Brazilian percussion, sophisticated harmonic movement, spacious organic production, nuanced Brazilian Portuguese vocal, poetic imagery, restrained verses and emotionally expanding chorus",exclude:"EDM, trap padrão, vocal grandioso, guitarra metal, clichês tropicais"},
  {slug:"bossa-nova",name:"Bossa nova",region:"Rio de Janeiro",family:"MPB",mood:"íntima, leve e noturna",bpm:"72–96",instruments:"violão nylon, baixo acústico, piano, bateria com vassourinhas",groove:"batida de bossa suave",vocal:"baixo, próximo e sem força excessiva",prompt:"Intimate Brazilian bossa nova, delicate nylon-string guitar syncopation, upright bass, brushed drums and sparse piano, warm late-night room, understated Brazilian Portuguese vocal, elegant harmony, subtle melodic phrasing, minimalist organic recording",exclude:"belting, big band explosiva, samba acelerado, synth bass, bateria eletrônica"},
  {slug:"funk-carioca",name:"Funk carioca",region:"Rio de Janeiro",family:"Funk brasileiro",mood:"ousado, urbano e corporal",bpm:"128–150",instruments:"tamborzão, subgrave, claps, synth curto",groove:"tamborzão sincopado",vocal:"rítmico, falado e de impacto",prompt:"Brazilian funk carioca, authentic tamborzão rhythm, heavy clean sub bass, sharp claps, sparse synthetic stabs, energetic baile atmosphere, rhythmic Brazilian Portuguese vocal, short punchlines, call and response, immediate viral hook, punchy club mix",exclude:"funk americano, reggaeton dembow, rock drums, piano romântico, arranjo orquestral"},
  {slug:"funk-melody",name:"Funk melody",region:"Rio de Janeiro",family:"Funk brasileiro",mood:"romântico, nostálgico e dançante",bpm:"118–132",instruments:"drum machine, synth pads, baixo eletrônico",groove:"funk com pulsação pop melódica",vocal:"melódico, doce e direto",prompt:"Brazilian funk melody, romantic electronic groove, classic drum-machine pulse, lush synth pads, melodic bass, nostalgic but modern atmosphere, emotional Brazilian Portuguese singing, simple verse, soaring memorable chorus, clean radio-ready production",exclude:"aggressive trap, metal guitars, acoustic folk, vocal rasgado, andamento muito rápido"},
  {
    slug: "trap-brasileiro",
    name: "Trap brasileiro",
    region: "Brasil urbano",
    family: "Rap e trap",
    mood: "ambição, tensão e presença",
    bpm: "128–150 half-time",
    instruments: "808, hi-hats, synth sombrio, piano esparso",
    groove: "half-time com variações de flow",
    vocal: "flow brasileiro, refrão melódico",
    prompt: "Brazilian trap, deep controlled 808, crisp rolling hi-hats, sparse dark piano and atmospheric synth texture, confident half-time groove, natural Brazilian Portuguese rap flow, concise verses, melodic earworm hook, dramatic transitions, polished spacious mix",
    exclude: "boom bap old school, reggaeton, rock guitars, choir épico, sotaque estrangeiro",
    referenceTracks: [{
      id: "beat-trap-01",
      label: "Beat Trap 01",
      audioUrl: "/beats/beat-trap-01.mp3",
      direction: "Trap brasileiro sombrio e espaçoso, 808 profundo, hi-hats nítidos, motivo melódico minimalista e flow em half-time.",
    }],
  },
  {slug:"boom-bap-br",name:"Boom bap brasileiro",region:"São Paulo",family:"Rap e trap",mood:"crítico, concreto e narrativo",bpm:"82–96",instruments:"drums secos, baixo sampleado, piano elétrico, scratches sutis",groove:"caixa marcada e pocket humano",vocal:"rima clara, cadência de rua",prompt:"Brazilian boom bap hip-hop, dusty punchy drums, warm sampled bass, sparse electric piano, subtle vinyl texture and occasional scratches, grounded São Paulo street atmosphere, articulate Brazilian Portuguese rap, dense storytelling verses, memorable spoken hook",exclude:"trap hi-hat rolls, autotune cantado, EDM synths, pop alegre, vocal em inglês"},
  {slug:"soul-brasileiro",name:"Soul brasileiro",region:"Brasil urbano",family:"Soul e R&B",mood:"quente, elegante e emocional",bpm:"72–98",instruments:"Rhodes, baixo elétrico, guitarra limpa, metais",groove:"pocket de soul com balanço brasileiro",vocal:"expressivo sem excesso de melismas",prompt:"Brazilian soul and contemporary R&B, warm Rhodes, expressive electric bass, clean guitar, subtle Brazilian percussion and tasteful horn accents, deep pocket, intimate Brazilian Portuguese vocal, emotional restraint, rich harmonies and a memorable soulful chorus",exclude:"excesso de melisma, trap dominante, EDM, rock pesado, coral gospel massivo"},
  {slug:"axé",name:"Axé",region:"Bahia",family:"Música baiana",mood:"solar, coletiva e explosiva",bpm:"124–146",instruments:"timbau, surdo, guitarra baiana, metais",groove:"percussão afro-baiana em camadas",vocal:"chamadas fortes e coro de multidão",prompt:"Brazilian Bahia axé, layered Afro-Brazilian percussion, timbau, surdo, bright guitarra baiana and festive brass, high-energy carnival groove, charismatic Brazilian Portuguese lead, powerful call and response, huge joyful chorus, vibrant live production",exclude:"trap, balada lenta, country, timbres sombrios, vocal sussurrado"},
  {slug:"samba-reggae",name:"Samba-reggae",region:"Bahia",family:"Música baiana",mood:"afirmativo, ritual e coletivo",bpm:"92–112",instruments:"surdo, repique, timbau, agogô",groove:"bloco afro, pesado e sincopado",vocal:"forte, comunitário e responsivo",prompt:"Bahian Brazilian samba-reggae, massive layered surdos, repique, timbau and agogô, deep Afro-Brazilian bloco groove, powerful communal energy, assertive Brazilian Portuguese lead with large response choir, ceremonial build and uplifting hook",exclude:"reggae jamaicano dominante, drum kit rock, synth pop, andamento acelerado de axé, vocal delicado"},
  {slug:"tecnobrega",name:"Tecnobrega",region:"Pará",family:"Norte eletrônico",mood:"romântico, popular e futurista",bpm:"120–138",instruments:"synths brilhantes, drum machine, guitarra processada",groove:"batida eletrônica de aparelhagem",vocal:"dramático e altamente melódico",prompt:"Brazilian Pará tecnobrega, bright maximalist synthesizers, punchy electronic dance drums, processed guitar accents, powerful aparelhagem sound-system energy, dramatic Brazilian Portuguese vocal, romantic verses, enormous catchy chorus, colorful futuristic production",exclude:"minimal techno, acoustic folk, sertanejo, rock pesado, vocal contido"},
  {slug:"carimbo",name:"Carimbó",region:"Pará",family:"Norte tradicional",mood:"terroso, circular e festivo",bpm:"104–126",instruments:"curimbó, maracas, banjo regional, flauta",groove:"dança circular marcada pelo tambor",vocal:"popular e celebratório",prompt:"Traditional Brazilian Pará carimbó, resonant curimbó drums, maracas, regional banjo and flute, circular dance rhythm, festive Amazonian coastal atmosphere, lively Brazilian Portuguese vocal, communal refrain, raw organic ensemble recording",exclude:"EDM, sertanejo, trap, bateria de rock, synths futuristas"},
  {slug:"frevo",name:"Frevo",region:"Pernambuco",family:"Carnaval pernambucano",mood:"urgente, virtuoso e eufórico",bpm:"150–190",instruments:"metais, caixa, bumbo, pratos",groove:"marcha sincopada veloz",vocal:"opcional, frases curtas e festivas",prompt:"Brazilian Pernambuco frevo, extremely energetic brass orchestra, agile trumpets and trombones, sharp snare, bass drum and cymbals, fast syncopated carnival march, virtuosic melodic lines, explosive street celebration, short joyful Brazilian Portuguese chants",exclude:"slow tempo, electronic bass, trap drums, romantic ballad, orchestral strings dominant"},
  {slug:"maracatu",name:"Maracatu nação",region:"Pernambuco",family:"Ritmos afro-brasileiros",mood:"majestoso, ancestral e pesado",bpm:"82–104",instruments:"alfaias, gonguê, caixas, agbê",groove:"baque virado em camadas",vocal:"toada forte com resposta coletiva",prompt:"Brazilian Pernambuco maracatu nação, thunderous layered alfaias, gonguê, snare drums and agbê, majestic baque virado groove, ancestral ceremonial atmosphere, commanding Brazilian Portuguese toada, communal response choir, powerful organic low end",exclude:"EDM kick, rock drum kit, samba-enredo, synth melody, vocal pop delicado"},
  {slug:"gospel-brasileiro",name:"Gospel brasileiro contemporâneo",region:"Brasil",family:"Gospel",mood:"esperança, entrega e crescimento",bpm:"68–92",instruments:"piano, pads, guitarra ambiente, bateria ampla",groove:"balada crescente com dinâmica",vocal:"emocional, claro e congregacional",prompt:"Contemporary Brazilian gospel worship, intimate piano opening, ambient guitar, warm pads, gradual live drum build, hopeful cinematic dynamics, sincere Brazilian Portuguese lead vocal, clear congregational melody, emotionally rising bridge and expansive final chorus",exclude:"trap beat, country americano, metal, excesso de melismas, início explosivo"},
  {slug:"pop-brasileiro",name:"Pop brasileiro",region:"Brasil",family:"Pop",mood:"imediato, colorido e emocional",bpm:"98–124",instruments:"synths, baixo pop, guitarra limpa, bateria híbrida",groove:"pop moderno com síncope brasileira",vocal:"natural, jovem e memorável",prompt:"Modern Brazilian pop, bright synth textures, clean guitar, punchy hybrid drums and melodic bass, subtle Brazilian rhythmic identity, intimate verse, tension-building pre-chorus, explosive concise chorus, natural Brazilian Portuguese vocal, polished streaming-ready production",exclude:"pop genérico em inglês, rock pesado, EDM drop longo, vocal infantil, letra excessivamente formal"},
];

export const structureTags = `[Intro]\n[Verse 1]\n[Pre-Chorus]\n[Chorus]\n[Verse 2]\n[Pre-Chorus]\n[Chorus]\n[Bridge]\n[Final Chorus]\n[Outro]`;
