"use client";
import { useMemo, useState } from "react";
import { AcademyShell } from "../../components/Portal";
export default function Compositor(){
  const [story,setStory]=useState("Eu quase desisti quando tudo parecia travado, mas continuei em silêncio até a primeira vitória aparecer.");
  const [person,setPerson]=useState("primeira pessoa"); const [language,setLanguage]=useState("popular, brasileira e conversada"); const [title,setTitle]=useState("Ainda de Pé"); const [copied,setCopied]=useState(false);
  const writingGuide=useMemo(()=>`Você é um compositor de música popular brasileira. Crie uma letra 100% original em português do Brasil.\n\nHISTÓRIA REAL:\n${story}\n\nDIREÇÃO:\n- Título provisório: ${title}\n- Ponto de vista: ${person}\n- Linguagem: ${language}\n- Use cenas, objetos, lugares e ações concretas\n- Preserve contradições humanas; não transforme tudo em motivação\n- Refrão curto, cantável e reconhecível na primeira audição\n- Versos com métrica relativamente consistente\n- Não cite artistas nem copie músicas existentes\n\nEVITE:\n- “voar”, “brilhar”, “jornada”, “destino” e “escuridão” como metáforas genéricas\n- rimas previsíveis em todas as linhas\n- explicar a moral da história\n- excesso de adjetivos e frases com cara de texto publicitário\n\nENTREGUE:\n1. Três opções de refrão\n2. A melhor opção escolhida e justificada em uma frase\n3. Letra completa com [Verse], [Pre-Chorus], [Chorus], [Bridge] e [Outro]\n4. Uma versão alternativa do primeiro verso com mais oralidade`,[story,person,language,title]);
  return <AcademyShell title="Roteiro de composição" eyebrow="LETRA HUMANA • MÉTODO GUIADO"><section className="composer-grid"><div className="composer-brief"><div className="eyebrow">MATÉRIA-PRIMA</div><h2>Não peça “uma letra bonita”.<br/><em>Dê uma vida para a música.</em></h2><label>Conte a cena ou história<textarea rows={8} value={story} onChange={e=>setStory(e.target.value)}/></label><div className="form-split"><label>Título provisório<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Ponto de vista<select value={person} onChange={e=>setPerson(e.target.value)}><option>primeira pessoa</option><option>segunda pessoa</option><option>terceira pessoa narrativa</option><option>diálogo entre duas pessoas</option></select></label></div><label>Tipo de linguagem<input value={language} onChange={e=>setLanguage(e.target.value)}/></label></div><article className="composer-output"><header><span>ROTEIRO DE LETRA</span><button onClick={async()=>{await navigator.clipboard.writeText(writingGuide);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?"COPIADO ✓":"COPIAR ROTEIRO"}</button></header><pre>{writingGuide}</pre></article></section><section className="human-checklist"><h2>Teste de humanidade</h2>{["Existe uma cena que dá para enxergar?","A pessoa falaria pelo menos uma frase desse jeito?","O refrão cabe na memória sem ler?","Há alguma contradição, detalhe imperfeito ou surpresa?","A letra evita parecer palestra, legenda ou anúncio?"].map((x,i)=><label key={x}><input type="checkbox"/><span>{String(i+1).padStart(2,"0")}</span>{x}</label>)}</section></AcademyShell>
}
